---
# - name: removing kube-proxy from kubernetes cluster.
#   shell: kubectl -n kube-system delete ds kube-proxy; kubectl -n kube-system delete cm kube-proxy; iptables-save | grep -v KUBE | iptables-restore
#   when: >
#     inventory_hostname in groups['kube_master'] and
#     groups['kube_master'].index(inventory_hostname) == 0

# - name: reseting iptables.
  # shell: iptables-save | grep -v KUBE | iptables-restore

- name: Ensure br_netfilter is enabled.
  shell: kubectl create secret generic -n kube-system cilium-etcd-secrets --from-file=etcd-client-ca.crt=/etc/kubernetes/pki/etcd-ca.pem --from-file=etcd-client.key=/etc/kubernetes/pki/etcd.key --from-file=etcd-client.crt=/etc/kubernetes/pki/etcd.cert

- name: etcd endpoint
  shell: |
    while IFS=$': \t' read -a line; \
    do [ -z "${line%inet}" ] && if [ $(echo -n ${line[1]} | wc -m) -gt 4 ]; then     ip=${line[1]}; else     ip=${line[2]}; fi && [ "${ip#127.0.0.1}" ] && myip=$ip; \
    done< <(LANG=C /sbin/ifconfig); echo $myip;
  register: internal_ip
  ignore_errors: true
  args:
    executable: /bin/bash

- name: Copy cilium manfiest files
  template: src="{{ item.src }}" dest="{{ item.dest }}"
  with_items:
     - { src: 'cilium.yaml.j2', dest: '/etc/kubernetes/cilium.yaml'  }  
  when: >
    inventory_hostname in groups['kube_master'] and
    groups['kube_master'].index(inventory_hostname) == 0

# - name: shell
#   shell: kubectl create -f /etc/kubernetes/cilium.yaml

