---
- name: Copy cilium manifest files
  template: src="{{ item.src }}" dest="{{ item.dest }}"
  with_items:
     - { src: 'ingress-nginx.yaml.j2', dest: '/etc/kubernetes/ingress-nginx.yaml'  }
  when: >
    inventory_hostname in groups['kube_master'] and
    groups['kube_master'].index(inventory_hostname) == 0

- name: applying ingress-nginx manifests
  shell: kubectl create -f /etc/kubernetes/ingress-nginx.yaml
  when: >
    inventory_hostname in groups['kube_master'] and
    groups['kube_master'].index(inventory_hostname) == 0

- name: removing ValidatingWebhookConfiguration to bypass the admission policy
  shell: kubectl delete -A ValidatingWebhookConfiguration ingress-nginx-admission
  when: >
    inventory_hostname in groups['kube_master'] and
    groups['kube_master'].index(inventory_hostname) == 0
